apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mochi-video-gen
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: mochi-backend
    app.kubernetes.io/part-of: mochi-video-gen
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: mochi-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP