apiVersion: v1
kind: Service
metadata:
  name: mochi-service
spec:
  selector:
    app: mochi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
  type: NodePort

