apiVersion: v1
kind: Namespace
metadata:
  name: mochi-video-gen
  labels:
    name: mochi-video-gen
    app.kubernetes.io/name: mochi-video-gen
    app.kubernetes.io/version: "1.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mochi-resource-quota
  namespace: mochi-video-gen
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 128Gi
    requests.nvidia.com/gpu: "8"
    limits.cpu: "64" 
    limits.memory: 256Gi
    limits.nvidia.com/gpu: "8"
    persistentvolumeclaims: "10"
    requests.storage: "20Ti"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mochi-limit-range
  namespace: mochi-video-gen
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "10Gi"
    defaultRequest:
      storage: "1Gi"
    max:
      storage: "20Ti"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim