apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mochi-video-gen
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: mochi-frontend
    app.kubernetes.io/part-of: mochi-video-gen
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: mochi-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: mochi-frontend
    spec:
      serviceAccountName: mochi-service-account
      initContainers:
      - name: wait-for-backend
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for backend service..."
          until nc -z backend-service 8000; do
            echo "Backend not ready, waiting..."
            sleep 5
          done
          echo "Backend is ready!"
      containers:
      - name: frontend
        image: glususer/mochi-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - frontend
              topologyKey: kubernetes.io/hostname