apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
  namespace: mochi-video-gen
  labels:
    app.kubernetes.io/name: ray-head
    app.kubernetes.io/instance: mochi-ray-head
    app.kubernetes.io/part-of: mochi-video-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ray-head
      app.kubernetes.io/instance: mochi-ray-head
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ray-head
        app.kubernetes.io/instance: mochi-ray-head
    spec:
      serviceAccountName: mochi-service-account
      containers:
      - name: ray-head
        image: glususer/mochi-ray:latest
        imagePullPolicy: Always
        ports:
        - name: ray-client
          containerPort: 10001
          protocol: TCP
        - name: ray-port
          containerPort: 6380
          protocol: TCP
        - name: ray-dashboard
          containerPort: 8265
          protocol: TCP
        env:
        - name: RAY_DISABLE_DOCKER_CPU_WARNING
          value: "1"
        - name: RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE
          value: "1"
        envFrom:
        - configMapRef:
            name: mochi-config
        resources:
          requests:
            cpu: 4
            memory: 16Gi
          limits:
            cpu: 8
            memory: 32Gi
        volumeMounts:
        - name: ray-tmp
          mountPath: /raytmp
        - name: cache-volume
          mountPath: /cache
        - name: models-volume
          mountPath: /models
        command:
        - /bin/bash
        - -c
        - |
          ray start \
            --head \
            --node-ip-address=0.0.0.0 \
            --num-cpus=4 \
            --num-gpus=0 \
            --port=6380 \
            --ray-client-server-port=10001 \
            --dashboard-host=0.0.0.0 \
            --dashboard-port=8265 \
            --temp-dir=/raytmp \
            --object-store-memory=4000000000 \
            --block
        livenessProbe:
          httpGet:
            path: /
            port: 8265
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8265
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: ray-tmp
        emptyDir:
          sizeLimit: 10Gi
      - name: cache-volume
        persistentVolumeClaim:
          claimName: cache-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "ray.io/node-type"
        operator: "Equal"
        value: "head"
        effect: "NoSchedule"