apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: mochi-video-gen
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: mochi-redis
    app.kubernetes.io/part-of: mochi-video-gen
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: mochi-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: mochi-redis
    spec:
      serviceAccountName: mochi-service-account
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        env:
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          defaultMode: 0644
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: mochi-redis
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: mochi-nvme-storage
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: mochi-video-gen
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: mochi-redis
data:
  redis.conf: |
    # Redis configuration for Mochi Video Generation
    port 6379
    bind 0.0.0.0
    
    # Memory management
    maxmemory 3gb
    maxmemory-policy allkeys-lru
    
    # Persistence - DISABLED due to volume permission issues
    save ""
    
    # Performance
    tcp-keepalive 300
    timeout 300
    
    # Logging
    loglevel notice
    
    # Security
    protected-mode no
    
    # Database
    databases 1